spring.application.name=api-gateway
server.port=8765

eureka.instance.prefer-ip-address=true
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true
auth.service.url=http://authorization-service:8089