spring.application.name=orders
server.port=8080
spring.profiles.active=local
spring.config.import=optional:file:./.env[.properties]
debug=false
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG
# Generate Swagger endpoints with for repositories
spring.data.rest.detection-strategy=annotated
# ApiCurrencyConverterService Properties
api.currency.converter.key=${CURRENCY_CONVERTER_API_KEY}
api.currency.converter.url=${CURRENCY_CONVERTER_URL}
# Eureka server config
eureka.instance.prefer-ip-address=true
# Resilience4j config
resilience4j.retry.instances.default.max-attempts=5
resilience4j.retry.instances.default.wait-duration=1s
resilience4j.retry.instances.default.enable-exponential-backoff=true
# ELK Logs path
logging.file.name=/tmp/logstash/logs/elk-stack.log
# Prometheus config
management.endpoints.web.exposure.include=prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true
#Micrometer tracing configuration
management.tracing.enabled=true
# Zipkin config
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans