spring.config.import=optional:file:../.env[.properties]
# Overriding docker dns with local dns
DB_URL=jdbc:postgresql://localhost:5432/generic
#spring.sql.init.data-locations=file:./db/data.sql

# Disable Eureka service discovery for tests
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
