package org.ecommerce;

import org.ecommerce.controllers.UserController;
import org.ecommerce.repositories.UserRepository;
import org.ecommerce.services.EmailService;
import org.ecommerce.services.PasswordService;
import org.ecommerce.services.impl.UserServiceImpl;
import org.ecommerce.services.impl.EmailServiceImpl;
import org.ecommerce.services.impl.PasswordServiceImpl;

import java.util.HashMap;
import java.util.Map;

public class Main {
    private static final Map<String, String> request = new HashMap<>();
    private static final UserRepository customerRepository = new UserRepository();
    private static final PasswordService passwordService = new PasswordServiceImpl(customerRepository);
    private static final EmailService emailService = new EmailServiceImpl();
    private static final UserServiceImpl customerService = new UserServiceImpl(customerRepository, passwordService, emailService);

    private static final UserController customerController = new UserController(customerService, passwordService);

    public static void main(String[] args) {
        request.put("id", "1"); // TODO: Shouldn't this id be generated by the db?
        request.put("firstName", "Brian");
        request.put("lastName", "Vega");
        request.put("email", "BrianVega@test.com");
        request.put("password", "@Password123");
        request.put("phoneNumber", "341234567");
        request.put("address", "Providencia #44");
        request.put("preferences", "preference1, preference2, preference3");

        var response = customerController.processCreationForm(request);

        if(response.containsKey("error")) System.out.println(response.get("error"));
        else System.out.println(response.get("generatedCustomer"));


        request.clear();
        request.put("id", "0"); // TODO: Shouldn't this id be generated by the db?
        request.put("oldPassword", "@Password123");
        request.put("newPassword", "@Password321");

        var responseUpdatePassword =  customerController.processChangePasswordForm(request);

        if(responseUpdatePassword.containsKey("error")) System.out.println(responseUpdatePassword.get("error"));
        else System.out.println(responseUpdatePassword.get("updatedUser"));
    }
}
